# Generated by Django 4.1.5 on 2023-01-25 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="trip_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
