# Generated by Django 4.1.5 on 2023-01-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="places",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
